VIDEO_DICT_LOCATION = "video_dict.txt"
FILE_DICT_LOCATION = "file_dict.txt"
DEFAULT_FOLDER = "vid_folders"
FINISHED_VIDEO_TYPE = ".mp4"
CLIP_VIDEO_TYPE = ".ts"
WEBDRIVER_LOCATION = r"C:/Selenium Drivers"
